# Permalinks
permalink:        pretty
relative_permalinks: true

include:  ['_pages']

collections:
  visions:
    output: true
    permalink: /visions/visions/
  activities:
    output: true
    permalink: /activities/:path/
  things:
    output: true
    permalink: /activities/things/:path/
  projects:
    output: true
    permalink: /activities/projects/:path/
  tanks:
    output: true
    permalink: /activities/tanks/:path/
  outs:
    output: true
    permalink: /activities/outs/:path/
  panels:
    output: true
    permalink: /activities/panels/:path/
  kaleidoscopes:
    output: true
    permalink: /activities/outs/:path/
  members:
    output: true
    permalink: /members/members/
  projects:
    output: true
    permalink: /projects/:path/
  store:
    output: true
    permalink: /store/:path/
  posts:
    output: true
    permalink: /posts/:path/
  news:
    output: true
    permalink: /news/:path/
relative_permalinks: false

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

# Setup
title:            Ink.
tagline:          Design Club at IIIT-Delhi
url:              ""
#url:              "http://localhost:4000"
baseurl:          "/"
imagesurl:		  /assets/images
logosurl:		  /assets/images/logos
headersurl:		  /assets/images/headers
projectimagesurl: /assets/images/projectimages
iconsurl: 		  /assets/images/icons
iconsurl: 		  /assets/members
docsurl: 		  /public/docs
twitter:		  https://twitter.com/iiitdink
facebook:		  https://www.facebook.com/ink.iiitd
trello:       https://trello.com/inkiiitd
behance:		  https://www.behance.net/ink-iiitd
maillist:			https://groups.google.com/forum/#!forum/ink-iiitd
mail:			    ink-admin@googlegroups.com

author:
  name:           'Sarthak Ahuja'
  url:            https://sarthakahuja.org

paginate:         5

# Custom vars
version:          1.0

github:
  themerepo:	    https://github.com/FrozenInk/soberOrg
  frozenink:      https://github.com/FrozenInk
  repo:      https://github.com/ink-iiitd/ink-iiitd.github.io

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]

